# User config
author: "SFPL"
tagline: "SFPL"
description: "We develop and grow transformative products that help shape humanity."
keywords: "software development, growth, marketing, user experience, san francisco"
email: "support@sfpl.io"
linkedin: "https://www.linkedin.com/company/25003042/"
twitter: "https://twitter.com/sfproductlabs"
github: "https://github.com/sfproductlabs"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
include: ["_redirects"]
