# User config
author: "SFPL"
tagline: "SFPL"
description: "Software, product and growth advisory. Our agency makes, delivers and grows ethical products and services."
desc: "We deliver and grow transformative technical, business and infrastructure products that help shape humanity."
keywords: "software, apps, computer and elecrical systems, software development, growth, marketing, user experience, australia, san francisco"
email: "support@sfpl.io"
linkedin: "https://www.linkedin.com/company/25003042/"
twitter: "https://twitter.com/sfproductlabs"
github: "https://github.com/sfproductlabs"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
include: ["_redirects"]
