# User config
author: "SF Product Labs"
tagline: "SF Product Labs"
description: "In 1493, explorer Christopher Columbus found pineapples on Guadeloupe Island in the Caribbean. Pineapple on pizza soon followed..."
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "support@sfproductlabs.com"
linkedin: "https://www.linkedin.com/company/25003042/"
twitter: "https://twitter.com/sfproductlabs"
github: "https://github.com/sfproductlabs"

# Site config
baseurl: "https://sfproductlabs.com/"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
