# User config
author: "SF Product Labs"
tagline: "SF Product Labs"
description: "We develop and grow transformative products that help shape humanity."
keywords: "software development, growth, marketing, user experience, san francisco"
email: "support@sfproductlabs.com"
linkedin: "https://www.linkedin.com/company/25003042/"
twitter: "https://twitter.com/sfproductlabs"
github: "https://github.com/sfproductlabs"

# Site config
baseurl: "https://sfproductlabs.com"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
include: ["_redirects"]
